language: python
sudo: required
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - export PYTHONPATH=./src:./src/models:./src/align
  - python -m unittest discover -s test --pattern=*.py 1>&2
dist: trusty

