language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: PYTHONPATH=./src ; python -m unittest discover -s test --pattern=*.py
dist: trusty

